import { TEST_COLOR_LIST } from '../details/TreeDetailsPage/constants'

let randomColor = [...Array(4)].map(() => TEST_COLOR_LIST[Math.floor(Math.random() * TEST_COLOR_LIST.length)])
export const TREE_VIEWER_TEST_DATA = [
  {
    name: '이설',
    decorationList: [
      {
        url: '/models/tree_1.glb',
        // urlList: ['/models/tree_1.glb', '/models/tree_2.glb', '/models/tree_3.glb', '/models/tree_4.glb'],
        position: [0, 0.3, 0],
        scale: [0.3, 0.3, 0.3],
        rotate: [0, 0, 0],
        type: 'GLB',
      },
      {
        color: randomColor[1],
        url: '/models/decoration_5_2.glb',
        // urlList: ['/models/decoration_5_1.glb', '/models/decoration_5_2.glb', '/models/decoration_5_3.glb'],
        position: [0, 0, 0.15],
        scale: [0.1, 0.1, 0.1],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[2],
        url: '/models/decoration_7_1.glb',
        // urlList: ['/models/decoration_7_1.glb', '/models/decoration_7_2.glb', '/models/decoration_7_3.glb'],
        position: [0, 0.2, -0.15],
        scale: [0.3, 0.3, 0.3],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[0],
        url: '/models/decoration_8_1.glb',
        // urlList: ['/models/decoration_8_1.glb', '/models/decoration_8_2.glb', '/models/decoration_8_3.glb'],
        position: [0, 0.4, 0],
        scale: [0.3, 0.3, 0.3],
        type: 'GLB',
      },
    ],
  },
  {
    name: '이민지',
    decorationList: [
      {
        url: '/models/tree_1.glb',
        // urlList: ['/models/tree_1.glb', '/models/tree_2.glb', '/models/tree_3.glb', '/models/tree_4.glb'],
        position: [0, 0.3, 0],
        scale: [0.3, 0.3, 0.3],
        rotate: [0, 0, 0],
        type: 'GLB',
      },
      {
        color: randomColor[1],
        url: '/models/decoration_5_3.glb',
        // urlList: ['/models/decoration_5_1.glb', '/models/decoration_5_2.glb', '/models/decoration_5_3.glb'],
        position: [0, 0, 0.15],
        scale: [0.1, 0.1, 0.1],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[2],
        url: '/models/decoration_7_2.glb',
        // urlList: ['/models/decoration_7_1.glb', '/models/decoration_7_2.glb', '/models/decoration_7_3.glb'],
        position: [0, 0.2, -0.15],
        scale: [0.3, 0.3, 0.3],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[0],
        url: '/models/decoration_8_2.glb',
        // urlList: ['/models/decoration_8_1.glb', '/models/decoration_8_2.glb', '/models/decoration_8_3.glb'],
        position: [0, 0.4, 0],
        scale: [0.3, 0.3, 0.3],
        type: 'GLB',
      },
    ],
  },
  {
    name: '황재형',
    decorationList: [
      {
        url: '/models/tree_1.glb',
        // urlList: ['/models/tree_1.glb', '/models/tree_2.glb', '/models/tree_3.glb', '/models/tree_4.glb'],
        position: [0, 0.3, 0],
        scale: [0.3, 0.3, 0.3],
        rotate: [0, 0, 0],
        type: 'GLB',
      },
      {
        color: randomColor[1],
        url: '/models/decoration_5_3.glb',
        // urlList: ['/models/decoration_5_1.glb', '/models/decoration_5_2.glb', '/models/decoration_5_3.glb'],
        position: [0, 0, 0.15],
        scale: [0.1, 0.1, 0.1],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[2],
        url: '/models/decoration_7_3.glb',
        // urlList: ['/models/decoration_7_1.glb', '/models/decoration_7_2.glb', '/models/decoration_7_3.glb'],
        position: [0, 0.2, -0.15],
        scale: [0.3, 0.3, 0.3],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[0],
        url: '/models/decoration_8_2.glb',
        // urlList: ['/models/decoration_8_1.glb', '/models/decoration_8_2.glb', '/models/decoration_8_3.glb'],
        position: [0, 0.4, 0],
        scale: [0.3, 0.3, 0.3],
        type: 'GLB',
      },
    ],
  },
  {
    name: '김동민',
    decorationList: [
      {
        url: '/models/tree_1.glb',
        // urlList: ['/models/tree_1.glb', '/models/tree_2.glb', '/models/tree_3.glb', '/models/tree_4.glb'],
        position: [0, 0.3, 0],
        scale: [0.3, 0.3, 0.3],
        rotate: [0, 0, 0],
        type: 'GLB',
      },
      {
        color: randomColor[1],
        url: '/models/decoration_5_3.glb',
        // urlList: ['/models/decoration_5_1.glb', '/models/decoration_5_2.glb', '/models/decoration_5_3.glb'],
        position: [0, 0, 0.15],
        scale: [0.1, 0.1, 0.1],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[2],
        url: '/models/decoration_7_3.glb',
        // urlList: ['/models/decoration_7_1.glb', '/models/decoration_7_2.glb', '/models/decoration_7_3.glb'],
        position: [0, 0.2, -0.15],
        scale: [0.3, 0.3, 0.3],
        rotate: [0.2, 0.3, 0.4],
        type: 'GLB',
      },
      {
        color: randomColor[0],
        url: '/models/decoration_8_2.glb',
        // urlList: ['/models/decoration_8_1.glb', '/models/decoration_8_2.glb', '/models/decoration_8_3.glb'],
        position: [0, 0.4, 0],
        scale: [0.3, 0.3, 0.3],
        type: 'GLB',
      },
    ],
  },
]
